### ISSUE TITLE
Refit

### ISSUE THREAD

**Issue by kiquenet** [jorgemhtdev/refit-xf#1]
Cómo usar Refit con OAuth2 y POST?

su lista de nuget imprescindibles para desarrollar en Xamarin Forms.?

**Comment by jorgemrht** [comment]
Puedes revisar los siguientes enlaces: https://jorgemht.com/posts/Refit#trabajar-con-refit y otra opción que me gusta es creando un custom HttpClient que ya tenga siempre en las cabeceras mi token: https://github.com/reactiveui/refit#authorization-dynamic-headers-redux

En todos los proyectos creo un HttpClient y siempre tengo algo similar a request.Headers.Authorization = new AuthenticationHeaderValue("bearer", token); para cada petición

Saludos, Jorge.
